### ISSUE TITLE
Converge on how we call them

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-extension-template#3]
ATM we use
- plugin, as a mechanism to "plug in" those beasts
- extension (package), as the external ones should be python packages, and as doc tune up in https://github.com/datalad/datalad/pull/2371 suggests
- module, as part of the name of this repository suggests

Why don't we just call them just either a `plugin` or an `extension`? 
Then there could be internal (which we ship within the main codebase), and external. They should indeed be implemented as "Python packages".  And then not mention the other one at all.
Then this template repo should be renamed accordingly to the decision (either `datalad-plugin-template` or `datalad-extension-template`)

**Comment by mih** [comment]
Yeah, I was dancing around this decision. I renamed this repo now: `datalad-extension-template`

Note, however, that a plugin and an extension are two different things and serve different purposes. I tried to describe the difference at the top of http://docs.datalad.org/en/docs/customization.html

**Comment by yarikoptic** [comment]
Ah right, extension is bigger...
But it is not worded out either they provide plugins for the commands?: 
extensions can provide any number of additional commands that can be grouped into labeled command suites, and are automatically exposed via the standard DataLad commandline and Python API

**Comment by mih** [comment]
I think http://docs.datalad.org/en/latest/customization.html#extension-packages says that and more. Not sure if you are hinting at something else?

**Comment by yarikoptic** [comment]
That is why I quoted that paragraph -- it talks about "Commands" and "suites", not a word about "plugins".

**Comment by mih** [comment]
Sorry, I don't get it. Extensions have nothing to do with plugins, why would they talk about it?
Anyways, don't try to convince me, just send the PR.
