### ISSUE TITLE
Make use of datalad/release-action

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-extension-template#48]
Now that we test driven it in DataLad proper, let's use in extensions.

**Comment by jwodder** [comment]
@yarikoptic This repo doesn't have any pre-existing semver labels.  Do you want the label names to be prefixed with "semver-" like in the DataLad repo or without the prefix like in the default `auto` setup?

**Comment by yarikoptic** [comment]
I guess the best would be to be consistent, so let's add that `semver-` prefix.  It should be done within this repo and then present in repositories to be templated from it.

**Comment by jwodder** [comment]
@yarikoptic Do you mean that you want the labels to be created and the workflows to run in this repo in addition to in templated repos?

**Comment by jwodder** [comment]
@yarikoptic Ping.

**Comment by yarikoptic** [comment]
So -- we want workflows to be present in this repo so they are "inherited" in the repositories which would be created based on this template. Do labels propagate also into repositories based on the template? if so -- we better have all the labels populated here. BUT since we are not making releases here, and do not want to have CHANGELOG modified etc by the workflows.  But that should not happen as long as we do not use any of those labels like `CHANGELOG-missing` or `release`.  Overall I think we should "instrument" this repository as if we wanted to make it use workflows but not really use  them.  Makes sense?

**Comment by jwodder** [comment]
@yarikoptic 

> Do labels propagate also into repositories based on the template?

It seems that they do not.

> Overall I think we should "instrument" this repository as if we wanted to make it use workflows but not really use them.

What does that mean?

**Comment by yarikoptic** [comment]
> @yarikoptic
> 
> > Do labels propagate also into repositories based on the template?
> 
> It seems that they do not.

Sad. Then no sense to add labels in this repo.
We need then helper and instructions in README on how to populate them in a new repo though.

> > Overall I think we should "instrument" this repository as if we wanted to make it use workflows but not really use them.
> 
> What does that mean?

That this repo would have all workflows but nobody should add any semver- etc label to pull requests here. If we don't have labels here though, nothing to worry about
