### ISSUE TITLE
Missing documentation/components for release action workflow

### ISSUE THREAD

**Issue by mih** [datalad/datalad-extension-template#54]
Readme says:

> Generate GitHub labels for use by the "Add changelog.d snippet" and "Auto-release on PR merge" workflows by using the code in the datalad/release-action repository as described in its README.

That README says run `nox` with a command that I translate to

```
GITHUB_TOKEN=... nox -e labels -- datalad/datalad-dataverse .datalad-release-action.yaml
```

and when I execute that I get

```
nox > Failed to load Noxfile /home/mih/hacking/datalad/dataverse/noxfile.py, no such file exists.
```

Either the instructions are incomplete, or the extension template should ship this file.

I was not aware of `nox` before, but it seems to be `tox` with a different configuration syntax.

**Comment by jwodder** [comment]
As stated in the release-action README, you need to run that command "in a clone of [the datalad/release-action] repository".

**Comment by mih** [comment]
Thanks for the clarification. I misunderstood the instructions.
