### ISSUE TITLE
appveyor virtualenv installation likely problematic

### ISSUE THREAD

**Issue by mih** [datalad/datalad-extension-template#67]
Check https://github.com/datalad/datalad-next/issues/441 for the description and the fix. I am not familiar with the problem, but I do not see why it would be specific to datalad-next -- hence also filing here.

**Comment by adswa** [comment]
Alternatively, @yarikoptic pointed out in the chat that he'd switched from the use of virtualenv to venv.

**Comment by mih** [comment]
I took a closer look on the original reasons for this setup. I can now confirm that the issue with the appveyor-provided venvs (LZMA not functional) has been resolved. This means that there is no need for any custom virtualenv or venv anymore.

I suggest that this complexity can be removed from the appveyor setup here. I have a patch that should do that for a new extension that I could port here.
