### ISSUE TITLE
Restructure docs

### ISSUE THREAD

**Issue by mslw** [datalad/datalad-extension-template#90]
The extension template puts all docs sections (API commands table, CLI commands list) in the main page, leading to IMHO awkward navigation panel:

![image](https://github.com/datalad/datalad-extension-template/assets/11985212/2b1f4a80-7d58-461b-a021-1b599f43e4d6)

I would propose switching to a more section-oriented layout, following or similar to: https://docs.datalad.org/projects/next/en/latest

**Comment by adswa** [comment]
I like this organization a lot tbh!

**Comment by mslw** [comment]
> I like this organization a lot tbh!

The one in the screenshot or the one in next? :smile:

**Comment by adswa** [comment]
Oh my bad, sorry :D I prefer the more sectioned layout in datalad-next :)
